### ISSUE TITLE
Frontend consistency

### ISSUE THREAD

**Issue by ez500** [GatherPack/gatherpack#171]
- [ ] When showing membership index, provide info button to go back to team show
- [ ] Membership table should probably be in a card body
- [ ] Capitalize first letter of every word of attributes/field titles (e.g. "Time Clock Period" instead of "Time clock period"
- [ ] Show all events in table or card group layout??
- [ ] Which category show views should we have "Back to [index]" for??? Brad plez answer thanks
- [ ] Remove unnecessary card sections (headers/bodies/footers) i.e., there's nothing in them
- [ ] Idk please comment with improvements to frontend

**Comment by braddoeswebdev** [comment]
Please don't make issues like this - there are 3 or 4 separate things here that should get broken out into individual issues.

Condensing multiple "small" tasks like this into one issue makes discussion more confusing & causes bottlenecks where completed work gets held up by discussion or concerns with completely unrelated stuff.

**Comment by ez500** [comment]
Sorry I didn't mean to push your buttons - I originally planned to use the misc branch to solve these misc problems and not link a PR to this issue, but simply close it. I don't know why this issue is pinned.
